name = "Miedo Modpack"
author = "somit"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8fefae6f933eaaa65545b5ea1916c20051e40e52b345dcdbb051d778e58100d"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
