name = "Miedo Modpack"
author = "somit"
version = "0.5.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44359017919f88e6e68383d1ca4fd38fbc51083a443a8690cb3981c0d5ac580e"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
