name = "Miedo Modpack"
author = "somit"
version = "0.5.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a7495033063da6328683a94f71dcb064abaa3923ae32b07fa65818dac26c518"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
